<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="7" passed="6">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="170" started-at="2017-07-17T13:36:21Z" finished-at="2017-07-17T13:36:22Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="170" started-at="2017-07-17T13:36:21Z" finished-at="2017-07-17T13:36:22Z">
      <class name="com.qainfotech.tap.training.snl.api.BoardModelTest">
        <test-method status="PASS" signature="dataTest()[pri:0, instance:com.qainfotech.tap.training.snl.api.BoardModelTest@56f4468b]" name="dataTest" duration-ms="4" started-at="2017-07-17T19:06:22Z" finished-at="2017-07-17T19:06:22Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- dataTest -->
        <test-method status="PASS" signature="initTest()[pri:0, instance:com.qainfotech.tap.training.snl.api.BoardModelTest@56f4468b]" name="initTest" duration-ms="5" started-at="2017-07-17T19:06:22Z" finished-at="2017-07-17T19:06:22Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initTest -->
        <test-method status="PASS" signature="saveTest()[pri:0, instance:com.qainfotech.tap.training.snl.api.BoardModelTest@56f4468b]" name="saveTest" duration-ms="8" started-at="2017-07-17T19:06:22Z" finished-at="2017-07-17T19:06:22Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- saveTest -->
      </class> <!-- com.qainfotech.tap.training.snl.api.BoardModelTest -->
      <class name="com.qainfotech.tap.training.snl.api.BoardTest">
        <test-method status="PASS" signature="registerPlayerTest()[pri:0, instance:com.qainfotech.tap.training.snl.api.BoardTest@5dfcfece]" name="registerPlayerTest" duration-ms="82" started-at="2017-07-17T19:06:21Z" finished-at="2017-07-17T19:06:22Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- registerPlayerTest -->
        <test-method status="FAIL" signature="registerPlayerTestForGameInProgressException()[pri:0, instance:com.qainfotech.tap.training.snl.api.BoardTest@5dfcfece]" name="registerPlayerTestForGameInProgressException" duration-ms="6" started-at="2017-07-17T19:06:22Z" finished-at="2017-07-17T19:06:22Z">
          <exception class="org.testng.TestException">
            <message>
              <![CDATA[
Method BoardTest.registerPlayerTestForGameInProgressException()[pri:0, instance:com.qainfotech.tap.training.snl.api.BoardTest@5dfcfece] should have thrown an exception of type class com.qainfotech.tap.training.snl.api.GameInProgressException]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.TestException: 
Method BoardTest.registerPlayerTestForGameInProgressException()[pri:0, instance:com.qainfotech.tap.training.snl.api.BoardTest@5dfcfece] should have thrown an exception of type class com.qainfotech.tap.training.snl.api.GameInProgressException
	at org.testng.internal.ExpectedExceptionsHolder.noException(ExpectedExceptionsHolder.java:89)
	at org.testng.internal.Invoker.handleInvocationResults(Invoker.java:1416)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:695)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.TestException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- registerPlayerTestForGameInProgressException -->
        <test-method status="PASS" signature="registerPlayerTestForMaxPlayerException()[pri:0, instance:com.qainfotech.tap.training.snl.api.BoardTest@5dfcfece]" name="registerPlayerTestForMaxPlayerException" duration-ms="16" started-at="2017-07-17T19:06:22Z" finished-at="2017-07-17T19:06:22Z">
          <exception class="com.qainfotech.tap.training.snl.api.MaxPlayersReachedExeption">
            <message>
              <![CDATA[The board already has maximum allowed Player: 4]]>
            </message>
            <full-stacktrace>
              <![CDATA[com.qainfotech.tap.training.snl.api.MaxPlayersReachedExeption: The board already has maximum allowed Player: 4
	at com.qainfotech.tap.training.snl.api.Board.registerPlayer(Board.java:70)
	at com.qainfotech.tap.training.snl.api.BoardTest.registerPlayerTestForMaxPlayerException(BoardTest.java:47)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- com.qainfotech.tap.training.snl.api.MaxPlayersReachedExeption -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- registerPlayerTestForMaxPlayerException -->
        <test-method status="PASS" signature="registerPlayerTestForPlayerExistException()[pri:0, instance:com.qainfotech.tap.training.snl.api.BoardTest@5dfcfece]" name="registerPlayerTestForPlayerExistException" duration-ms="11" started-at="2017-07-17T19:06:22Z" finished-at="2017-07-17T19:06:22Z">
          <exception class="com.qainfotech.tap.training.snl.api.PlayerExistsException">
            <message>
              <![CDATA[Player 'vids' already exists on board]]>
            </message>
            <full-stacktrace>
              <![CDATA[com.qainfotech.tap.training.snl.api.PlayerExistsException: Player 'vids' already exists on board
	at com.qainfotech.tap.training.snl.api.Board.registerPlayer(Board.java:75)
	at com.qainfotech.tap.training.snl.api.BoardTest.registerPlayerTestForPlayerExistException(BoardTest.java:60)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- com.qainfotech.tap.training.snl.api.PlayerExistsException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- registerPlayerTestForPlayerExistException -->
      </class> <!-- com.qainfotech.tap.training.snl.api.BoardTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
